### ISSUE TITLE
Make test coverage trackable

### ISSUE THREAD

**Issue by skapral** [project-avral/oo-atom#134]
- by displaying the coverage badge at project's start page
- by failing the build if coverage thresholds is below some level.

**Comment by 0pdd** [comment]
@skapral the puzzle [#145](https://github.com/project-avral/oo-atom/issues/145) is still not solved.

**Comment by 0pdd** [comment]
@skapral the puzzle [#195](https://github.com/pragmatic-objects/oo-atom/issues/195) is still not solved.
