### ISSUE TITLE
Refactor checkstyle configuration

### ISSUE THREAD

**Issue by skapral** [project-avral/oo-atom#165]
1. Add rules enforcing javadoc validation.
2. Outline checkstyle configuration to a separate xml file.

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#167](https://github.com/project-avral/oo-atom/issues/167), [#168](https://github.com/project-avral/oo-atom/issues/168), [#169](https://github.com/project-avral/oo-atom/issues/169) are still not solved.

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#180](https://github.com/pragmatic-objects/oo-atom/issues/180), [#183](https://github.com/pragmatic-objects/oo-atom/issues/183), [#197](https://github.com/pragmatic-objects/oo-atom/issues/197) are still not solved.

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#180](https://github.com/pragmatic-objects/oo-atom/issues/180), [#197](https://github.com/pragmatic-objects/oo-atom/issues/197) are still not solved; solved: [#183](https://github.com/pragmatic-objects/oo-atom/issues/183).

**Comment by 0pdd** [comment]
@skapral the puzzle [#197](https://github.com/pragmatic-objects/oo-atom/issues/197) is still not solved; solved: [#180](https://github.com/pragmatic-objects/oo-atom/issues/180), [#183](https://github.com/pragmatic-objects/oo-atom/issues/183).
