### ISSUE TITLE
Move assertions to main part of the project

### ISSUE THREAD

**Issue by skapral** [project-avral/oo-atom#47]
Assertions, as a part of the project, must be covered with unit tests.

**Comment by 0pdd** [comment]
@skapral 4 puzzles [#186](https://github.com/pragmatic-objects/oo-atom/issues/186), [#187](https://github.com/pragmatic-objects/oo-atom/issues/187), [#188](https://github.com/pragmatic-objects/oo-atom/issues/188), [#189](https://github.com/pragmatic-objects/oo-atom/issues/189) are still not solved; solved: [#190](https://github.com/pragmatic-objects/oo-atom/issues/190), [#191](https://github.com/pragmatic-objects/oo-atom/issues/191), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#186](https://github.com/pragmatic-objects/oo-atom/issues/186), [#187](https://github.com/pragmatic-objects/oo-atom/issues/187), [#189](https://github.com/pragmatic-objects/oo-atom/issues/189) are still not solved; solved: [#188](https://github.com/pragmatic-objects/oo-atom/issues/188), [#190](https://github.com/pragmatic-objects/oo-atom/issues/190), [#191](https://github.com/pragmatic-objects/oo-atom/issues/191), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#186](https://github.com/pragmatic-objects/oo-atom/issues/186), [#187](https://github.com/pragmatic-objects/oo-atom/issues/187) are still not solved; solved: [#188](https://github.com/pragmatic-objects/oo-atom/issues/188), [#189](https://github.com/pragmatic-objects/oo-atom/issues/189), [#190](https://github.com/pragmatic-objects/oo-atom/issues/190), [#191](https://github.com/pragmatic-objects/oo-atom/issues/191), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral the puzzle [#186](https://github.com/pragmatic-objects/oo-atom/issues/186) is still not solved; solved: [#187](https://github.com/pragmatic-objects/oo-atom/issues/187), [#188](https://github.com/pragmatic-objects/oo-atom/issues/188), [#189](https://github.com/pragmatic-objects/oo-atom/issues/189), [#190](https://github.com/pragmatic-objects/oo-atom/issues/190), [#191](https://github.com/pragmatic-objects/oo-atom/issues/191), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral all 11 puzzles are solved here: [#186](https://github.com/pragmatic-objects/oo-atom/issues/186), [#187](https://github.com/pragmatic-objects/oo-atom/issues/187), [#188](https://github.com/pragmatic-objects/oo-atom/issues/188), [#189](https://github.com/pragmatic-objects/oo-atom/issues/189), [#190](https://github.com/pragmatic-objects/oo-atom/issues/190), [#191](https://github.com/pragmatic-objects/oo-atom/issues/191), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().
