### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by skapral** [project-avral/oo-atom#8]

**Comment by 0pdd** [comment]
@skapral 13 puzzles [#108](https://github.com/project-avral/oo-atom/issues/108), [#109](https://github.com/project-avral/oo-atom/issues/109), [#148](https://github.com/project-avral/oo-atom/issues/148), [#44](https://github.com/project-avral/oo-atom/issues/44), [#45](https://github.com/project-avral/oo-atom/issues/45), [#46](https://github.com/project-avral/oo-atom/issues/46), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@skapral 3 puzzles [#184](https://github.com/pragmatic-objects/oo-atom/issues/184), [#185](https://github.com/pragmatic-objects/oo-atom/issues/185), [#194](https://github.com/pragmatic-objects/oo-atom/issues/194) are still not solved; solved: [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#184](https://github.com/pragmatic-objects/oo-atom/issues/184), [#185](https://github.com/pragmatic-objects/oo-atom/issues/185) are still not solved; solved: [#194](https://github.com/pragmatic-objects/oo-atom/issues/194), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral the puzzle [#184](https://github.com/pragmatic-objects/oo-atom/issues/184) is still not solved; solved: [#185](https://github.com/pragmatic-objects/oo-atom/issues/185), [#194](https://github.com/pragmatic-objects/oo-atom/issues/194), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().

**Comment by 0pdd** [comment]
@skapral all 13 puzzles are solved here: [#184](https://github.com/pragmatic-objects/oo-atom/issues/184), [#185](https://github.com/pragmatic-objects/oo-atom/issues/185), [#194](https://github.com/pragmatic-objects/oo-atom/issues/194), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().
